; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Wed Dec 18 2019 16:02:09 GMT+0200 (Eastern European Standard Time)
M280 P0 S10 ;I1 ; deploy BLTouch

